name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Export environment variables
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ vars.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ vars.FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV
          echo "CYPRESS_FIREBASE_EMULATOR_HOST=${{ vars.FIREBASE_EMULATOR_HOST }}" >> $GITHUB_ENV
          echo "CYPRESS_FIREBASE_API_KEY=${{ vars.FIREBASE_API_KEY }}" >> $GITHUB_ENV

      - name: Run end-to-end tests
        run: yarn run test:e2e